name: Scala Steward

# This workflow will launch at 00:00 every day
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  scala-steward:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup build
        uses: ./.github/actions/setup-build
        with:
          targetPlatform: 11
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          author-name: scala-steward
          author-email: scala-steward
          github-token: ${{ secrets.REPO_GITHUB_TOKEN }}
          repo-config: .scala-steward.conf
          ignore-opts-files: false
      - name: Cleanup build
        uses: ./.github/actions/cleanup-build
